server:
  port: ${APP_PORT:8080}
spring:
  application:
    name: report
  devtools:
    add-properties: false
aws:
  dynamodb:
    region: ${DYNAMODB_REGION}
    table:
      credit-summary: ${DYNAMODB_CREDIT_SUMMARY_TABLE}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: http://localhost:4200,http://localhost:8080
app:
  paths:
    credit-summary:
      summary: /report/api/v1/report
jwt:
  secret: ${JWT_SECRET}
logging:
  level:
    com.crediya: ${LOG_LEVEL:INFO}
entrypoint:
  sqs:
    credit-approved:
      region: ${SQS_APPROVED_REPORT_REGION}
      queueUrl: ${SQS_APPROVED_REPORT_QUEUE_URL}
      waitTimeSeconds: 20
      maxNumberOfMessages: 10
      visibilityTimeoutSeconds: 10
      numberOfThreads: 1
  scheduler:
    pool-size: 1
    wait-terminate-seconds: 30
    jobs:
      cron-daily-report: ${CRON_DAILY_REPORT}
adapter:
  sqs:
    region: ${SQS_SCHEDULED_REPORT_REGION}
    queueUrl: ${SQS_SCHEDULED_REPORT_QUEUE_URL}
